CREATE DATABASE TRNG;
USE TRNG;
CREATE TABLE chunks (chunk VARCHAR(256), created DATETIME);
CREATE TABLE clients (client VARCHAR(32), issued INT(11));
CREATE USER 'TRNG'@'localhost' IDENTIFIED BY 'TRNGTRNG';
GRANT ALL PRIVILEGES ON TRNG.* TO 'TRNG'@'localhost';
FLUSH PRIVILEGES;

